Remove license symlinks
Cargo doesn't like this:

    error: failed to prepare local package for uploading

    Caused by:
      failed to open for archiving: `/Users/pascal/Projekte/waltz/waltz/LICENSE-APACHE